export const wars = [
  // Ancient
  { name: "Greco-Persian Wars", start: -499, end: -449, casualties: 300000, region: "Europe/Middle East", scale: "major", belligerents: "Greek city-states vs Achaemenid Empire", type: "Interstate" },
  { name: "Peloponnesian War", start: -431, end: -404, casualties: 100000, region: "Europe", scale: "major", belligerents: "Athens vs Sparta", type: "Interstate" },
  { name: "Wars of Alexander the Great", start: -336, end: -323, casualties: 250000, region: "Europe/Asia", scale: "major", belligerents: "Macedon vs Persian Empire & others", type: "Conquest" },
  { name: "Punic Wars", start: -264, end: -146, casualties: 1500000, region: "Europe/Africa", scale: "major", belligerents: "Rome vs Carthage", type: "Interstate" },
  { name: "Gallic Wars", start: -58, end: -50, casualties: 1000000, region: "Europe", scale: "major", belligerents: "Rome vs Gallic tribes", type: "Conquest" },
  { name: "Roman Civil Wars", start: -49, end: -31, casualties: 200000, region: "Europe", scale: "major", belligerents: "Roman factions", type: "Civil War" },
  
  // Medieval
  { name: "Muslim Conquests", start: 622, end: 750, casualties: 500000, region: "Middle East/Africa/Europe", scale: "major", belligerents: "Arab Caliphates vs various", type: "Conquest" },
  { name: "Viking Invasions", start: 793, end: 1066, casualties: 200000, region: "Europe", scale: "minor", belligerents: "Norse vs European kingdoms", type: "Raids/Conquest" },
  { name: "Crusades (1st-9th)", start: 1096, end: 1291, casualties: 3000000, region: "Middle East/Europe", scale: "major", belligerents: "Christian Europe vs Muslim states", type: "Religious" },
  { name: "Mongol Conquests", start: 1206, end: 1368, casualties: 40000000, region: "Asia/Europe/Middle East", scale: "major", belligerents: "Mongol Empire vs various", type: "Conquest" },
  { name: "Hundred Years' War", start: 1337, end: 1453, casualties: 3500000, region: "Europe", scale: "major", belligerents: "England vs France", type: "Interstate" },
  { name: "Wars of the Roses", start: 1455, end: 1487, casualties: 50000, region: "Europe", scale: "minor", belligerents: "House of Lancaster vs House of York", type: "Civil War" },
  { name: "Fall of Constantinople", start: 1453, end: 1453, casualties: 50000, region: "Europe/Middle East", scale: "minor", belligerents: "Ottoman Empire vs Byzantine Empire", type: "Conquest" },
  
  // Early Modern
  { name: "Italian Wars", start: 1494, end: 1559, casualties: 300000, region: "Europe", scale: "minor", belligerents: "France, Spain, HRE & Italian states", type: "Interstate" },
  { name: "Spanish Conquest of Aztec Empire", start: 1519, end: 1521, casualties: 300000, region: "Americas", scale: "minor", belligerents: "Spain vs Aztec Empire", type: "Conquest" },
  { name: "French Wars of Religion", start: 1562, end: 1598, casualties: 3000000, region: "Europe", scale: "major", belligerents: "French Catholics vs Huguenots", type: "Civil War/Religious" },
  { name: "Eighty Years' War", start: 1568, end: 1648, casualties: 600000, region: "Europe", scale: "minor", belligerents: "Dutch Republic vs Spain", type: "Independence" },
  { name: "Thirty Years' War", start: 1618, end: 1648, casualties: 8000000, region: "Europe", scale: "major", belligerents: "Protestant vs Catholic states", type: "Religious/Interstate" },
  { name: "English Civil War", start: 1642, end: 1651, casualties: 200000, region: "Europe", scale: "minor", belligerents: "Parliamentarians vs Royalists", type: "Civil War" },
  { name: "Great Turkish War", start: 1683, end: 1699, casualties: 300000, region: "Europe/Middle East", scale: "minor", belligerents: "Holy League vs Ottoman Empire", type: "Interstate" },
  { name: "War of Spanish Succession", start: 1701, end: 1714, casualties: 1200000, region: "Europe", scale: "major", belligerents: "Grand Alliance vs France & Spain", type: "Interstate" },
  { name: "Seven Years' War", start: 1756, end: 1763, casualties: 1400000, region: "Global", scale: "major", belligerents: "Britain & Prussia vs France & Austria", type: "Interstate" },
  { name: "American Revolutionary War", start: 1775, end: 1783, casualties: 70000, region: "Americas", scale: "minor", belligerents: "American colonies vs Britain", type: "Independence" },
  { name: "French Revolution Wars", start: 1792, end: 1802, casualties: 700000, region: "Europe", scale: "major", belligerents: "France vs European coalitions", type: "Interstate" },
  
  // 19th Century
  { name: "Napoleonic Wars", start: 1803, end: 1815, casualties: 6500000, region: "Europe/Global", scale: "major", belligerents: "France vs European coalitions", type: "Interstate" },
  { name: "War of 1812", start: 1812, end: 1815, casualties: 30000, region: "Americas", scale: "minor", belligerents: "United States vs Britain", type: "Interstate" },
  { name: "Greek War of Independence", start: 1821, end: 1829, casualties: 170000, region: "Europe", scale: "minor", belligerents: "Greece vs Ottoman Empire", type: "Independence" },
  { name: "First Opium War", start: 1839, end: 1842, casualties: 25000, region: "Asia", scale: "minor", belligerents: "Britain vs Qing China", type: "Interstate" },
  { name: "Mexican-American War", start: 1846, end: 1848, casualties: 40000, region: "Americas", scale: "minor", belligerents: "United States vs Mexico", type: "Interstate" },
  { name: "Crimean War", start: 1853, end: 1856, casualties: 500000, region: "Europe", scale: "minor", belligerents: "Allied powers vs Russia", type: "Interstate" },
  { name: "Taiping Rebellion", start: 1850, end: 1864, casualties: 30000000, region: "Asia", scale: "major", belligerents: "Qing dynasty vs Taiping Heavenly Kingdom", type: "Civil War" },
  { name: "American Civil War", start: 1861, end: 1865, casualties: 750000, region: "Americas", scale: "major", belligerents: "Union vs Confederacy", type: "Civil War" },
  { name: "Franco-Prussian War", start: 1870, end: 1871, casualties: 250000, region: "Europe", scale: "minor", belligerents: "Prussia/German states vs France", type: "Interstate" },
  { name: "Russo-Turkish War", start: 1877, end: 1878, casualties: 260000, region: "Europe/Middle East", scale: "minor", belligerents: "Russia vs Ottoman Empire", type: "Interstate" },
  { name: "First Sino-Japanese War", start: 1894, end: 1895, casualties: 50000, region: "Asia", scale: "minor", belligerents: "Japan vs Qing China", type: "Interstate" },
  { name: "Spanish-American War", start: 1898, end: 1898, casualties: 10000, region: "Americas/Asia", scale: "minor", belligerents: "United States vs Spain", type: "Interstate" },
  { name: "Second Boer War", start: 1899, end: 1902, casualties: 75000, region: "Africa", scale: "minor", belligerents: "Britain vs Boer republics", type: "Colonial" },
  
  // 20th Century
  { name: "Russo-Japanese War", start: 1904, end: 1905, casualties: 150000, region: "Asia", scale: "minor", belligerents: "Russia vs Japan", type: "Interstate" },
  { name: "Balkan Wars", start: 1912, end: 1913, casualties: 200000, region: "Europe", scale: "minor", belligerents: "Balkan states vs Ottoman Empire", type: "Interstate" },
  { name: "World War I", start: 1914, end: 1918, casualties: 20000000, region: "Global", scale: "major", belligerents: "Allies vs Central Powers", type: "Interstate" },
  { name: "Russian Civil War", start: 1917, end: 1922, casualties: 9000000, region: "Europe/Asia", scale: "major", belligerents: "Bolsheviks vs White Army & others", type: "Civil War" },
  { name: "Irish War of Independence", start: 1919, end: 1921, casualties: 2100, region: "Europe", scale: "minor", belligerents: "Irish Republic vs Britain", type: "Independence" },
  { name: "Greco-Turkish War", start: 1919, end: 1922, casualties: 200000, region: "Europe/Middle East", scale: "minor", belligerents: "Greece vs Turkey", type: "Interstate" },
  { name: "Chinese Civil War", start: 1927, end: 1949, casualties: 8000000, region: "Asia", scale: "major", belligerents: "Nationalists vs Communists", type: "Civil War" },
  { name: "Spanish Civil War", start: 1936, end: 1939, casualties: 500000, region: "Europe", scale: "minor", belligerents: "Republicans vs Nationalists", type: "Civil War" },
  { name: "Second Sino-Japanese War", start: 1937, end: 1945, casualties: 20000000, region: "Asia", scale: "major", belligerents: "China vs Japan", type: "Interstate" },
  { name: "World War II", start: 1939, end: 1945, casualties: 75000000, region: "Global", scale: "major", belligerents: "Allies vs Axis Powers", type: "Interstate" },
  { name: "First Indochina War", start: 1946, end: 1954, casualties: 500000, region: "Asia", scale: "minor", belligerents: "Viet Minh vs France", type: "Independence" },
  { name: "Arab-Israeli War 1948", start: 1948, end: 1949, casualties: 20000, region: "Middle East", scale: "minor", belligerents: "Israel vs Arab states", type: "Interstate" },
  { name: "Korean War", start: 1950, end: 1953, casualties: 2500000, region: "Asia", scale: "major", belligerents: "South Korea & UN vs North Korea & China", type: "Interstate" },
  { name: "Algerian War", start: 1954, end: 1962, casualties: 1500000, region: "Africa", scale: "minor", belligerents: "FLN vs France", type: "Independence" },
  { name: "Vietnam War", start: 1955, end: 1975, casualties: 3500000, region: "Asia", scale: "major", belligerents: "South Vietnam & US vs North Vietnam & Viet Cong", type: "Interstate/Civil" },
  { name: "Six-Day War", start: 1967, end: 1967, casualties: 24000, region: "Middle East", scale: "minor", belligerents: "Israel vs Egypt, Jordan, Syria", type: "Interstate" },
  { name: "Nigerian Civil War", start: 1967, end: 1970, casualties: 2000000, region: "Africa", scale: "minor", belligerents: "Nigeria vs Biafra", type: "Civil War" },
  { name: "Bangladesh Liberation War", start: 1971, end: 1971, casualties: 3000000, region: "Asia", scale: "minor", belligerents: "East Pakistan & India vs Pakistan", type: "Independence" },
  { name: "Yom Kippur War", start: 1973, end: 1973, casualties: 20000, region: "Middle East", scale: "minor", belligerents: "Israel vs Egypt & Syria", type: "Interstate" },
  { name: "Ethiopian Civil War", start: 1974, end: 1991, casualties: 1400000, region: "Africa", scale: "minor", belligerents: "Derg vs rebel groups", type: "Civil War" },
  { name: "Cambodian-Vietnamese War", start: 1977, end: 1991, casualties: 200000, region: "Asia", scale: "minor", belligerents: "Vietnam vs Khmer Rouge", type: "Interstate" },
  { name: "Soviet-Afghan War", start: 1979, end: 1989, casualties: 2000000, region: "Asia", scale: "major", belligerents: "Soviet Union vs Mujahideen", type: "Interstate" },
  { name: "Iran-Iraq War", start: 1980, end: 1988, casualties: 1000000, region: "Middle East", scale: "major", belligerents: "Iran vs Iraq", type: "Interstate" },
  { name: "Falklands War", start: 1982, end: 1982, casualties: 900, region: "Americas", scale: "minor", belligerents: "UK vs Argentina", type: "Interstate" },
  { name: "Gulf War", start: 1990, end: 1991, casualties: 40000, region: "Middle East", scale: "minor", belligerents: "Coalition vs Iraq", type: "Interstate" },
  { name: "Yugoslav Wars", start: 1991, end: 2001, casualties: 140000, region: "Europe", scale: "minor", belligerents: "Yugoslav successor states", type: "Civil War/Interstate" },
  { name: "Rwandan Civil War & Genocide", start: 1990, end: 1994, casualties: 1000000, region: "Africa", scale: "major", belligerents: "RPF vs Hutu government", type: "Civil War/Genocide" },
  { name: "First Chechen War", start: 1994, end: 1996, casualties: 50000, region: "Europe/Asia", scale: "minor", belligerents: "Russia vs Chechnya", type: "Independence" },
  { name: "Second Congo War", start: 1998, end: 2003, casualties: 5400000, region: "Africa", scale: "major", belligerents: "Multiple African nations", type: "Interstate/Civil" },
  { name: "Second Chechen War", start: 1999, end: 2009, casualties: 80000, region: "Europe/Asia", scale: "minor", belligerents: "Russia vs Chechen separatists", type: "Civil War" },
  
  // 21st Century
  { name: "War in Afghanistan", start: 2001, end: 2021, casualties: 240000, region: "Asia", scale: "major", belligerents: "US & NATO vs Taliban", type: "Interstate" },
  { name: "Iraq War", start: 2003, end: 2011, casualties: 500000, region: "Middle East", scale: "major", belligerents: "US-led coalition vs Iraq/insurgents", type: "Interstate" },
  { name: "War in Darfur", start: 2003, end: 2020, casualties: 400000, region: "Africa", scale: "minor", belligerents: "Sudanese government vs rebel groups", type: "Civil War" },
  { name: "Syrian Civil War", start: 2011, end: 2024, casualties: 600000, region: "Middle East", scale: "major", belligerents: "Multiple factions", type: "Civil War" },
  { name: "Yemeni Civil War", start: 2014, end: 2024, casualties: 380000, region: "Middle East", scale: "minor", belligerents: "Houthis vs Saudi-backed government", type: "Civil War" },
  { name: "Russo-Ukrainian War", start: 2022, end: 2025, casualties: 500000, region: "Europe", scale: "major", belligerents: "Russia vs Ukraine", type: "Interstate" },
];
